### ISSUE TITLE
#pragma target 5.0->3.0 would be better to support mobile platforms www

### ISSUE THREAD

**Issue by superowner** [gkjohnson/unity-clip-shader#6]
#pragma target 5.0->3.0 would be better to support mobile platforms www

**Comment by gkjohnson** [comment]
Thanks! I'll bump it down next chance I get

**Comment by gkjohnson** [comment]
Fixed https://github.com/gkjohnson/unity-clip-shader/commit/ae5afa0f4da891c3f30e8249bea5301a647aed49
